import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        marginTop: 20,
        backgroundColor: '#f1f1f1',
        borderBottomWidth: 1,
        borderBottomColor: '#ddd',
    },
    logo: {
        width: 80,
        height: 80,
        marginRight: 10,
    },
    headerTitle: {
        fontSize: 20,
        fontFamily: 'Monoton',
        color: '#333',
    },
    red: {
        color: '#ff3131',
        fontFamily: 'Monoton',
    },
    addScreenBody: {
        flex: 1,
        padding: 20,
        backgroundColor: '#f1f1f1',
    },
    header2:{
        flexDirection: 'row',
        gap:8,
    },
    titolo: {
        fontSize: 24,
        fontFamily: 'Fredoka',
        color: '#333',
        marginBottom: 20,
    },
    buttons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 20,
    },
    goBackButton: {
        padding: 10,
        backgroundColor: '#ff3131',
        borderRadius: 5,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 5,
        marginLeft: 'auto',
    },
    modifyButton: {
        padding: 10,
        backgroundColor: '#ff3131',
        borderRadius: 5,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 5,
    },
    modifyButtontext: {
        color: '#fff',
        fontFamily: 'Fredoka',
    },
    addButton: {
        padding: 10,
        backgroundColor: '#ff3131',
        borderRadius: 5,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 5,
    },
    addButtontext: {
        color: '#fff',
        fontFamily: 'Fredoka',
    },
    formContainer: {
        marginTop: 20,
        backgroundColor: '#f1f1f1',
        padding: 20,
        borderRadius: 10,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 5,
    },
    label: {
        fontSize: 16,
        fontFamily: 'Fredoka',
        color: '#a6a6a6',
        marginBottom: 5,
    },
     subtext: {
        fontSize: 12,
        fontFamily: 'Fredoka',
        color: '#a6a6a6',
        marginBottom: 5,
    },
    input: {
        height: 40,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 5,
        paddingHorizontal: 10,
        marginBottom: 15,
        backgroundColor: '#f1f1f1',
    },
});
export default styles;